### ISSUE TITLE
为什么依赖jetbrain ai插件？

### ISSUE THREAD

**Issue by xflcx1991** [ClearPlume/jimmer-dto#18]
我的idea删除了  ai assistant插件。是2024.2版本。下载 jimmerDTO插件，在idea数据库面板的表右击，在生成时均会在idea右下角提示插件有崩溃。

信息如下
> java.lang.Throwable: top.fallenangel.jimmergenerator.component.SettingStorageComponent <clinit> requests com.intellij.openapi.client.ClientSessionsManager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
    at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
    at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents$default(ComponentManagerImpl.kt:307)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:304)
    at com.intellij.openapi.project.impl.DefaultProjectImpl.init(DefaultProject.kt:236)
    at com.intellij.openapi.project.impl.DefaultProject$timedProject$1.init(DefaultProject.kt:59)
    at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:30)
    at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.kt:118)
    at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.kt:177)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.kt:232)
    at top.fallenangel.jimmergenerator.component.SettingStorageComponent.<clinit>(SettingStorageComponent.kt:30)
    at top.fallenangel.jimmergenerator.MainEntry.actionPerformed(MainEntry.kt:42)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:342)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks$lambda$4(ActionUtil.kt:313)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1172)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.kt:312)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction$lambda$5(ActionMenuItem.kt:271)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:231)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.kt:262)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem._init_$lambda$0(ActionMenuItem.kt:71)
    at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed$lambda$4(ActionMenuItem.kt:102)
    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.kt:101)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:518)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:551)
    at java.desktop/java.awt.Component.processMouseEvent(Component.java:6662)
    at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)

看到有openai字样，我猜测是不是和ai插件有关，又装回来但禁用（开启也用不了啊）果然这样的提示就没了。
问题来了为什么这个插件要依赖ai assistant插件

![image](https://github.com/user-attachments/assets/a5dbcf50-e29b-4e57-af5f-08c638b03463)

**Comment by xflcx1991** [comment]
装回  ai assistant插件，仍然有插件的报错，只是内容变了。

> com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'net.fallingangel.jimmerdto.action.CreateJimmerDtoFile' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: net.fallingangel.jimmer-dto]
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
    at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
    at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
    at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by xflcx1991** [comment]
看错了，是这个插件的问题。本issue关闭
